#!/bin/bash
[ ! -d build ] && mkdir build
rm -rf build/*
cd build
#cmake -DCMAKE_BUILD_TYPE=Debug/Release ../admin/
cmake ../admin/
#colormake
make
cd ../
[ ! -d bin ] && mkdir bin
mv build/simulator_scr bin/simulator_scr
mv build/driver_scr bin/driver_scr
ln -sf bin/simulator_scr simulator
ln -sf bin/driver_scr driver
